const ADD_TODO = "ADD_TODO";
const DELETE_TODO = "DELETE_TODO";
const LIST_DONE = "LIST_DONE";
const LIST_REMOVE_DONE = "LIST_REMOVE_DONE";
const FILTER_SEARCH = 'FILTER_SEARCH';
const EDIT_TODO = 'EDIT_TODO';
const UPDATE_TODO = 'UPDATE_TODO';
const DELETE_COMPLETED_TODO = "DELETE_COMPLETED_TODO";

export { ADD_TODO, DELETE_TODO, LIST_DONE, LIST_REMOVE_DONE, FILTER_SEARCH, EDIT_TODO, UPDATE_TODO, DELETE_COMPLETED_TODO }